# Generated by Django 5.0.2 on 2024-07-26 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_author_demo_feild_alter_author_bio'),
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='author_blogs', to='author.author'),
        ),
        migrations.CreateModel(
            name='CoverImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_link', models.URLField()),
                ('blog', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='blog_ci', to='myblog.blog')),
            ],
        ),
    ]
